naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    active: true
    excludes: ['**/ui/theme/**', '**/theme/**']
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '0xFF2E7D32'
  ReturnCount:
    max: 5
